// source: src/network/services/influencer_public_profile_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var src_network_services_influencer_profile_pb = require('../../../src/network/services/influencer_profile_pb.js');
goog.object.extend(proto, src_network_services_influencer_profile_pb);
goog.exportSymbol('proto.influencer.GetInfluencerPublicProfileRequest', null, global);
goog.exportSymbol('proto.influencer.GetInfluencerPublicProfileResponse', null, global);
goog.exportSymbol('proto.influencer.GetInfluencerPublicProfileResponse.Error', null, global);
goog.exportSymbol('proto.influencer.GetInfluencerPublicProfileResponse.Error.ErrorType', null, global);
goog.exportSymbol('proto.influencer.GetInfluencerPublicProfileResponse.StateCase', null, global);
goog.exportSymbol('proto.influencer.GetInfluencerPublicProfileResponse.Success', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.influencer.GetInfluencerPublicProfileRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.influencer.GetInfluencerPublicProfileRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.influencer.GetInfluencerPublicProfileRequest.displayName = 'proto.influencer.GetInfluencerPublicProfileRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.influencer.GetInfluencerPublicProfileResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.influencer.GetInfluencerPublicProfileResponse.oneofGroups_);
};
goog.inherits(proto.influencer.GetInfluencerPublicProfileResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.influencer.GetInfluencerPublicProfileResponse.displayName = 'proto.influencer.GetInfluencerPublicProfileResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.influencer.GetInfluencerPublicProfileResponse.Success = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.influencer.GetInfluencerPublicProfileResponse.Success, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.influencer.GetInfluencerPublicProfileResponse.Success.displayName = 'proto.influencer.GetInfluencerPublicProfileResponse.Success';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.influencer.GetInfluencerPublicProfileResponse.Error = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.influencer.GetInfluencerPublicProfileResponse.Error, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.influencer.GetInfluencerPublicProfileResponse.Error.displayName = 'proto.influencer.GetInfluencerPublicProfileResponse.Error';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.influencer.GetInfluencerPublicProfileRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.influencer.GetInfluencerPublicProfileRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.influencer.GetInfluencerPublicProfileRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.influencer.GetInfluencerPublicProfileRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    username: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.influencer.GetInfluencerPublicProfileRequest}
 */
proto.influencer.GetInfluencerPublicProfileRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.influencer.GetInfluencerPublicProfileRequest;
  return proto.influencer.GetInfluencerPublicProfileRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.influencer.GetInfluencerPublicProfileRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.influencer.GetInfluencerPublicProfileRequest}
 */
proto.influencer.GetInfluencerPublicProfileRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUsername(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.influencer.GetInfluencerPublicProfileRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.influencer.GetInfluencerPublicProfileRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.influencer.GetInfluencerPublicProfileRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.influencer.GetInfluencerPublicProfileRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUsername();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string username = 1;
 * @return {string}
 */
proto.influencer.GetInfluencerPublicProfileRequest.prototype.getUsername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.influencer.GetInfluencerPublicProfileRequest} returns this
 */
proto.influencer.GetInfluencerPublicProfileRequest.prototype.setUsername = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.influencer.GetInfluencerPublicProfileResponse.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.influencer.GetInfluencerPublicProfileResponse.StateCase = {
  STATE_NOT_SET: 0,
  SUCCESS: 1,
  ERROR: 2
};

/**
 * @return {proto.influencer.GetInfluencerPublicProfileResponse.StateCase}
 */
proto.influencer.GetInfluencerPublicProfileResponse.prototype.getStateCase = function() {
  return /** @type {proto.influencer.GetInfluencerPublicProfileResponse.StateCase} */(jspb.Message.computeOneofCase(this, proto.influencer.GetInfluencerPublicProfileResponse.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.influencer.GetInfluencerPublicProfileResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.influencer.GetInfluencerPublicProfileResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.influencer.GetInfluencerPublicProfileResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.influencer.GetInfluencerPublicProfileResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    success: (f = msg.getSuccess()) && proto.influencer.GetInfluencerPublicProfileResponse.Success.toObject(includeInstance, f),
    error: (f = msg.getError()) && proto.influencer.GetInfluencerPublicProfileResponse.Error.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.influencer.GetInfluencerPublicProfileResponse}
 */
proto.influencer.GetInfluencerPublicProfileResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.influencer.GetInfluencerPublicProfileResponse;
  return proto.influencer.GetInfluencerPublicProfileResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.influencer.GetInfluencerPublicProfileResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.influencer.GetInfluencerPublicProfileResponse}
 */
proto.influencer.GetInfluencerPublicProfileResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.influencer.GetInfluencerPublicProfileResponse.Success;
      reader.readMessage(value,proto.influencer.GetInfluencerPublicProfileResponse.Success.deserializeBinaryFromReader);
      msg.setSuccess(value);
      break;
    case 2:
      var value = new proto.influencer.GetInfluencerPublicProfileResponse.Error;
      reader.readMessage(value,proto.influencer.GetInfluencerPublicProfileResponse.Error.deserializeBinaryFromReader);
      msg.setError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.influencer.GetInfluencerPublicProfileResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.influencer.GetInfluencerPublicProfileResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.influencer.GetInfluencerPublicProfileResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.influencer.GetInfluencerPublicProfileResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSuccess();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.influencer.GetInfluencerPublicProfileResponse.Success.serializeBinaryToWriter
    );
  }
  f = message.getError();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.influencer.GetInfluencerPublicProfileResponse.Error.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.influencer.GetInfluencerPublicProfileResponse.Success.prototype.toObject = function(opt_includeInstance) {
  return proto.influencer.GetInfluencerPublicProfileResponse.Success.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.influencer.GetInfluencerPublicProfileResponse.Success} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.influencer.GetInfluencerPublicProfileResponse.Success.toObject = function(includeInstance, msg) {
  var f, obj = {
    profile: (f = msg.getProfile()) && src_network_services_influencer_profile_pb.InfluencerProfile.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.influencer.GetInfluencerPublicProfileResponse.Success}
 */
proto.influencer.GetInfluencerPublicProfileResponse.Success.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.influencer.GetInfluencerPublicProfileResponse.Success;
  return proto.influencer.GetInfluencerPublicProfileResponse.Success.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.influencer.GetInfluencerPublicProfileResponse.Success} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.influencer.GetInfluencerPublicProfileResponse.Success}
 */
proto.influencer.GetInfluencerPublicProfileResponse.Success.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new src_network_services_influencer_profile_pb.InfluencerProfile;
      reader.readMessage(value,src_network_services_influencer_profile_pb.InfluencerProfile.deserializeBinaryFromReader);
      msg.setProfile(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.influencer.GetInfluencerPublicProfileResponse.Success.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.influencer.GetInfluencerPublicProfileResponse.Success.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.influencer.GetInfluencerPublicProfileResponse.Success} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.influencer.GetInfluencerPublicProfileResponse.Success.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProfile();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      src_network_services_influencer_profile_pb.InfluencerProfile.serializeBinaryToWriter
    );
  }
};


/**
 * optional InfluencerProfile profile = 1;
 * @return {?proto.influencer.InfluencerProfile}
 */
proto.influencer.GetInfluencerPublicProfileResponse.Success.prototype.getProfile = function() {
  return /** @type{?proto.influencer.InfluencerProfile} */ (
    jspb.Message.getWrapperField(this, src_network_services_influencer_profile_pb.InfluencerProfile, 1));
};


/**
 * @param {?proto.influencer.InfluencerProfile|undefined} value
 * @return {!proto.influencer.GetInfluencerPublicProfileResponse.Success} returns this
*/
proto.influencer.GetInfluencerPublicProfileResponse.Success.prototype.setProfile = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.influencer.GetInfluencerPublicProfileResponse.Success} returns this
 */
proto.influencer.GetInfluencerPublicProfileResponse.Success.prototype.clearProfile = function() {
  return this.setProfile(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.influencer.GetInfluencerPublicProfileResponse.Success.prototype.hasProfile = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.influencer.GetInfluencerPublicProfileResponse.Error.prototype.toObject = function(opt_includeInstance) {
  return proto.influencer.GetInfluencerPublicProfileResponse.Error.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.influencer.GetInfluencerPublicProfileResponse.Error} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.influencer.GetInfluencerPublicProfileResponse.Error.toObject = function(includeInstance, msg) {
  var f, obj = {
    errorType: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.influencer.GetInfluencerPublicProfileResponse.Error}
 */
proto.influencer.GetInfluencerPublicProfileResponse.Error.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.influencer.GetInfluencerPublicProfileResponse.Error;
  return proto.influencer.GetInfluencerPublicProfileResponse.Error.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.influencer.GetInfluencerPublicProfileResponse.Error} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.influencer.GetInfluencerPublicProfileResponse.Error}
 */
proto.influencer.GetInfluencerPublicProfileResponse.Error.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.influencer.GetInfluencerPublicProfileResponse.Error.ErrorType} */ (reader.readEnum());
      msg.setErrorType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.influencer.GetInfluencerPublicProfileResponse.Error.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.influencer.GetInfluencerPublicProfileResponse.Error.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.influencer.GetInfluencerPublicProfileResponse.Error} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.influencer.GetInfluencerPublicProfileResponse.Error.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getErrorType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.influencer.GetInfluencerPublicProfileResponse.Error.ErrorType = {
  UNKNOWN: 0,
  PROFILE_DOES_NOT_EXIST: 1,
  PROFILE_NOT_LIVE: 2
};

/**
 * optional ErrorType error_type = 1;
 * @return {!proto.influencer.GetInfluencerPublicProfileResponse.Error.ErrorType}
 */
proto.influencer.GetInfluencerPublicProfileResponse.Error.prototype.getErrorType = function() {
  return /** @type {!proto.influencer.GetInfluencerPublicProfileResponse.Error.ErrorType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.influencer.GetInfluencerPublicProfileResponse.Error.ErrorType} value
 * @return {!proto.influencer.GetInfluencerPublicProfileResponse.Error} returns this
 */
proto.influencer.GetInfluencerPublicProfileResponse.Error.prototype.setErrorType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional Success success = 1;
 * @return {?proto.influencer.GetInfluencerPublicProfileResponse.Success}
 */
proto.influencer.GetInfluencerPublicProfileResponse.prototype.getSuccess = function() {
  return /** @type{?proto.influencer.GetInfluencerPublicProfileResponse.Success} */ (
    jspb.Message.getWrapperField(this, proto.influencer.GetInfluencerPublicProfileResponse.Success, 1));
};


/**
 * @param {?proto.influencer.GetInfluencerPublicProfileResponse.Success|undefined} value
 * @return {!proto.influencer.GetInfluencerPublicProfileResponse} returns this
*/
proto.influencer.GetInfluencerPublicProfileResponse.prototype.setSuccess = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.influencer.GetInfluencerPublicProfileResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.influencer.GetInfluencerPublicProfileResponse} returns this
 */
proto.influencer.GetInfluencerPublicProfileResponse.prototype.clearSuccess = function() {
  return this.setSuccess(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.influencer.GetInfluencerPublicProfileResponse.prototype.hasSuccess = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Error error = 2;
 * @return {?proto.influencer.GetInfluencerPublicProfileResponse.Error}
 */
proto.influencer.GetInfluencerPublicProfileResponse.prototype.getError = function() {
  return /** @type{?proto.influencer.GetInfluencerPublicProfileResponse.Error} */ (
    jspb.Message.getWrapperField(this, proto.influencer.GetInfluencerPublicProfileResponse.Error, 2));
};


/**
 * @param {?proto.influencer.GetInfluencerPublicProfileResponse.Error|undefined} value
 * @return {!proto.influencer.GetInfluencerPublicProfileResponse} returns this
*/
proto.influencer.GetInfluencerPublicProfileResponse.prototype.setError = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.influencer.GetInfluencerPublicProfileResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.influencer.GetInfluencerPublicProfileResponse} returns this
 */
proto.influencer.GetInfluencerPublicProfileResponse.prototype.clearError = function() {
  return this.setError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.influencer.GetInfluencerPublicProfileResponse.prototype.hasError = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.influencer);
